import 'package:flutter/foundation.dart';

class LanguageProvider extends ChangeNotifier {
  String _languageCode = 'en';
  String get languageCode => _languageCode;
  void setLanguage(String code) {
    if (code != 'en' && code != 'ta') return;
    if (_languageCode == code) return;
    _languageCode = code;
    AppLocalization.languageCode = code;
    notifyListeners();
  }
}

class AppLocalization {
  static String languageCode = 'en';
  static String t(String key) => languageCode == 'ta' ? (_ta[key] ?? key) : key;
  static const Map<String, String> _ta = {
    'Dashboard': 'டாஷ்போர்டு',
    'Excavators': 'எக்ஸ்கவேட்டர்கள்',
    'Excavator': 'எக்ஸ்கவேட்டர்',
    'Excavator Maintenance': 'எக்ஸ்கவேட்டர் பராமரிப்பு',
    'Excavator Service': 'எக்ஸ்கவேட்டர் சேவை',
    'Transport': 'போக்குவரத்து',
    'Transport Maintenance': 'போக்குவரத்து பராமரிப்பு',
    'Transport Service': 'போக்குவரத்து சேவை',
    'Operations & Audit': 'செயல்பாடுகள் & தணிக்கை',
    'Service Notifications': 'சேவை அறிவிப்புகள்',
    'Reports': 'அறிக்கைகள்',
    'Compliance': 'இணக்கப்பாடு',
    'Inventory': 'சரக்கு',
    'Inventory Dashboard': 'சரக்கு டாஷ்போர்டு',
    'Spare Stock': 'உதிரி பாக இருப்பு',
    'Spare Purchase & OCR': 'உதிரி பாக கொள்முதல் & OCR',
    'Spare Usage': 'உதிரி பாக பயன்பாடு',
    'Inventory Reports': 'சரக்கு அறிக்கைகள்',
    'Quarry Blasting': 'குவாரி பிளாஸ்டிங்',
    'Quarry Operations': 'குவாரி செயல்பாடுகள்',
    'Quarry Boulders': 'குவாரி கற்கள்',
    'Quarry Boulders Reports': 'குவாரி கற்கள் அறிக்கைகள்',
    'Quarry Boulders Trip Details': 'குவாரி கற்கள் பயண விவரங்கள்',
    'Record quarry-to-crusher lorry trips and calculate total load from trip × unit.':
        'குவாரி முதல் க்ரஷர் வரை லாரி பயணங்களைப் பதிவு செய்து, பயணம் × அலகு அடிப்படையில் மொத்த சுமையை கணக்கிடுங்கள்.',
    'Daily, weekly, monthly and yearly trip/load summaries.':
        'தினசரி, வாராந்திர, மாதாந்திர மற்றும் வருடாந்திர பயணம் / சுமை சுருக்கங்கள்.',
    'Add Trip': 'பயணத்தைச் சேர்',
    'Edit Quarry Boulders Trip': 'குவாரி கற்கள் பயணத்தைத் திருத்து',
    'Add Quarry Boulders Trip': 'குவாரி கற்கள் பயணத்தைச் சேர்',
    'Save Trip': 'பயணத்தைச் சேமி',
    'Update Trip': 'பயணத்தைப் புதுப்பி',
    'Trip': 'பயணம்',
    'Total Load': 'மொத்த சுமை',
    'Unit': 'அலகு',
    'Enter unit per trip': 'ஒரு பயணத்திற்கான அலகை உள்ளிடவும்',
    'Enter a valid unit': 'சரியான அலகை உள்ளிடவும்',
    'Lorry Registration No': 'லாரி பதிவு எண்',
    'Search registration number...': 'பதிவு எண்ணைத் தேடுக...',
    'Search driver name...': 'ஓட்டுநர் பெயரைத் தேடுக...',
    'Driver Name': 'ஓட்டுநர் பெயர்',
    'All Drivers': 'அனைத்து ஓட்டுநர்கள்',
    'Add Driver': 'ஓட்டுநரைச் சேர்',
    'Select driver': 'ஓட்டுநரைத் தேர்ந்தெடுக்கவும்',
    'Company cannot be selected as a driver.': 'Company-ஐ ஓட்டுநராகத் தேர்ந்தெடுக்க முடியாது.',
    'All Operators': 'அனைத்து ஆபரேட்டர்கள்',
    'Add Operator': 'ஆபரேட்டரைச் சேர்',
    'Salary': 'சம்பளம்',
    'Add Manually': 'கைமுறையாகச் சேர்',
    'Add Item': 'பொருளைச் சேர்',
    'Enter valid purchase item details.': 'சரியான கொள்முதல் பொருள் விவரங்களை உள்ளிடவும்.',
    'Diesel Consumption (L/H)': 'டீசல் பயன்பாடு (லிட்டர் / மணி)',

    'Select Date': 'தேதியைத் தேர்ந்தெடுக்கவும்',
    'Enter driver name': 'ஓட்டுநர் பெயரை உள்ளிடவும்',
    'Select lorry registration number': 'லாரி பதிவு எண்ணைத் தேர்ந்தெடுக்கவும்',
    'Enter valid trip count': 'சரியான பயண எண்ணிக்கையை உள்ளிடவும்',
    'Load is calculated automatically as Trip × Unit.':
        'மொத்த சுமை பயணம் × அலகு அடிப்படையில் தானாக கணக்கிடப்படும்.',
    'Selected lorry does not have a unit configured. Please ask an administrator to configure the unit in Transport Master.':
        'தேர்ந்தெடுத்த லாரிக்கு அலகு அமைக்கப்படவில்லை. Transport Master-ல் அலகை அமைக்க நிர்வாகியிடம் கேட்கவும்.',
    'Not configured': 'அமைக்கப்படவில்லை',
    'Trip saved successfully.': 'பயணம் வெற்றிகரமாகச் சேமிக்கப்பட்டது.',
    'Trip updated successfully.': 'பயணம் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது.',
    'Trip deleted successfully.': 'பயணம் வெற்றிகரமாக நீக்கப்பட்டது.',
    'Delete Trip?': 'பயணத்தை நீக்கவா?',
    'This trip record will be permanently deleted. This action cannot be undone.':
        'இந்த பயணப் பதிவு நிரந்தரமாக நீக்கப்படும். இந்த செயலை மீண்டும் மாற்ற முடியாது.',
    'No quarry boulder trip records found.':
        'குவாரி கற்கள் பயணப் பதிவுகள் எதுவும் இல்லை.',
    'Total Records': 'மொத்த பதிவுகள்',
    'Total Trips': 'மொத்த பயணங்கள்',
    'Drivers': 'ஓட்டுநர்கள்',
    'Showing': 'காட்டுகிறது',
    'of': 'இல்',
    'Driver-wise Summary': 'ஓட்டுநர் வாரியான சுருக்கம்',
    'Lorry-wise Summary': 'லாரி வாரியான சுருக்கம்',
    'Records': 'பதிவுகள்',
    'No report data available.': 'அறிக்கை தரவு இல்லை.',
    'Report Type': 'அறிக்கை வகை',
    'Daily': 'தினசரி',
    'Weekly': 'வாராந்திரம்',
    'Yearly': 'வருடாந்திரம்',
    'Custom': 'தனிப்பயன்',
    'Generate': 'உருவாக்கு',
    'Search Vehicle': 'வாகனத்தைத் தேடுக',
    'Registration number...': 'பதிவு எண்ணை உள்ளிடவும்...',
    'Blasting Dashboard': 'பிளாஸ்டிங் டாஷ்போர்டு',
    'Purchase History': 'கொள்முதல் வரலாறு',
    'Blasting Reports': 'பிளாஸ்டிங் அறிக்கைகள்',
    'Administrator': 'நிர்வாகி',
    'User': 'பயனர்',
    'Logout': 'வெளியேறு',
    'Language': 'மொழி',
    'Actions': 'செயல்கள்',
    'ACTIONS': 'செயல்கள்',
    'Active': 'செயலில்',
    'Inactive': 'செயலில் இல்லை',
    'All': 'அனைத்தும்',
    'All Compliance': 'அனைத்து இணக்கப்பாடுகள்',
    'All Equipment': 'அனைத்து உபகரணங்கள்',
    'All Items': 'அனைத்து பொருட்கள்',
    'All Shifts': 'அனைத்து ஷிப்ட்கள்',
    'All Status': 'அனைத்து நிலைகள்',
    'All Statuses': 'அனைத்து நிலைகள்',
    'All Vehicles': 'அனைத்து வாகனங்கள்',
    'Apply Filters': 'வடிகட்டிகளை பயன்படுத்து',
    'Clear': 'அழி',
    'Cancel': 'ரத்து',
    'Close': 'மூடு',
    'Change': 'மாற்று',
    'Save': 'சேமி',
    'Delete': 'நீக்கு',
    'Edit': 'திருத்து',
    'View': 'பார்',
    'Add': 'சேர்',
    'Export': 'ஏற்றுமதி',
    'Export Excel': 'Excel ஏற்றுமதி',
    'Excel report saved successfully.':
        'Excel அறிக்கை வெற்றிகரமாகச் சேமிக்கப்பட்டது.',
    'Export PDF': 'PDF ஏற்றுமதி',
    'Print': 'அச்சிடு',
    'Refresh': 'புதுப்பி',
    'Retry': 'மீண்டும் முயற்சி',
    'OK': 'சரி',
    'Continue': 'தொடரவும்',
    'Confirm & Save': 'உறுதிசெய்து சேமி',
    'Please wait...': 'தயவுசெய்து காத்திருக்கவும்...',
    'Date': 'தேதி',
    'Day': 'நாள்',
    'Monthly': 'மாதாந்திரம்',
    'YEAR': 'ஆண்டு',
    'Hours': 'மணிநேரம்',
    'Current Hours': 'தற்போதைய மணிநேரம்',
    'Current KM': 'தற்போதைய கி.மீ.',
    'Start KM': 'தொடக்க கி.மீ.',
    'Closing KM': 'முடிவு கி.மீ.',
    'Total KM': 'மொத்த கி.மீ.',
    'HOUR METER': 'மணி மீட்டர்',
    'Shift': 'ஷிப்ட்',
    'Operator': 'ஆபரேட்டர்',
    'Driver': 'ஓட்டுநர்',
    'Vehicle': 'வாகனம்',
    'Select a vehicle.': 'ஒரு வாகனத்தைத் தேர்ந்தெடுக்கவும்.',
    'Select Excavator': 'எக்ஸ்கவேட்டரைத் தேர்ந்தெடுக்கவும்',
    'Select date': 'தேதியைத் தேர்ந்தெடுக்கவும்',
    'Maintenance': 'பராமரிப்பு',
    'Service': 'சேவை',
    'Remarks': 'குறிப்புகள்',
    'Remarks (Optional)': 'குறிப்புகள் (விருப்பம்)',
    'Cost': 'செலவு',
    'Total Cost': 'மொத்த செலவு',
    'TOTAL COST': 'மொத்த செலவு',
    'Grand Total Cost': 'மொத்த இறுதி செலவு',
    'Quantity': 'அளவு',
    'Quantity (Litres)': 'அளவு (லிட்டர்)',
    'QTY': 'அளவு',
    'Rate': 'விலை விகிதம்',
    'UNIT': 'அலகு',
    'UNIT PRICE': 'அலகு விலை',
    'SUBTOTAL': 'கூட்டுத்தொகை',
    'Tax': 'வரி',
    'GST %': 'GST %',
    'PURCHASE COST': 'கொள்முதல் செலவு',
    'PURCHASED': 'கொள்முதல்',
    'PURCHASED QTY': 'கொள்முதல் அளவு',
    'REMAINING': 'மீதம்',
    'REMAINING QTY': 'மீதமுள்ள அளவு',
    'USED': 'பயன்படுத்தியது',
    'USED QTY': 'பயன்படுத்திய அளவு',
    'USED FOR': 'பயன்படுத்திய நோக்கம்',
    'SPARE ITEM': 'உதிரி பாகம்',
    'SUPPLIER': 'சப்ளையர்',
    'Supplier (Optional)': 'சப்ளையர் (விருப்பம்)',
    'Bill Number (Optional)': 'பில் எண் (விருப்பம்)',
    'BILL NUMBER': 'பில் எண்',
    'REGISTRATION': 'பதிவு எண்',
    'EQUIPMENT': 'உபகரணம்',
    'MANUFACTURER': 'உற்பத்தியாளர்',
    'MODEL': 'மாடல்',
    'Insurance': 'காப்பீடு',
    'Permit': 'அனுமதி',
    'Diesel': 'டீசல்',
    'Diesel Lorry / Source': 'டீசல் லாரி / மூலம்',
    'Diesel Rate': 'டீசல் விலை',
    'Diesel Used': 'பயன்படுத்திய டீசல்',
    'Diesel Stock Summary': 'டீசல் இருப்பு சுருக்கம்',
    'Fillings': 'நிரப்பல்கள்',
    'Recent Diesel Filling': 'சமீபத்திய டீசல் நிரப்பல்',
    'Vehicle-wise Diesel Consumption': 'வாகன வாரியான டீசல் பயன்பாடு',
    'Add Diesel Receipt': 'டீசல் ரசீதை சேர்',
    'Add Receipt': 'ரசீதை சேர்',
    'Save Filling': 'நிரப்பலை சேமி',
    'Opening': 'தொடக்க இருப்பு',
    'Closing': 'முடிவு இருப்பு',
    'Transaction': 'பரிவர்த்தனை',
    'Stock Movement': 'இருப்பு நகர்வு',
    'Current Stock': 'தற்போதைய இருப்பு',
    'Previous Stock': 'முந்தைய இருப்பு',
    'Record Usage': 'பயன்பாட்டை பதிவு செய்',
    'Record Spare Usage': 'உதிரி பாக பயன்பாட்டை பதிவு செய்',
    'Upload Bill': 'பில் பதிவேற்று',
    'Upload Image': 'படத்தை பதிவேற்று',
    'Use Image': 'படத்தை பயன்படுத்து',
    'Extracting Data': 'தரவை பிரித்தெடுக்கிறது',
    'Review Extracted Data': 'பிரித்தெடுத்த தரவை சரிபார்',
    'Use These Values': 'இந்த மதிப்புகளை பயன்படுத்து',
    'Uploaded Sheet': 'பதிவேற்றிய ஷீட்',
    'New Purchase': 'புதிய கொள்முதல்',
    'Purchase Details': 'கொள்முதல் விவரங்கள்',
    'Add Spare': 'உதிரி பாகத்தை சேர்',
    'Add Vehicle': 'வாகனத்தை சேர்',
    'Add Excavator': 'எக்ஸ்கவேட்டரை சேர்',
    'Add Maintenance': 'பராமரிப்பை சேர்',
    'Add Service': 'சேவையை சேர்',
    'Update Excavator': 'எக்ஸ்கவேட்டரை புதுப்பி',
    'Update Vehicle': 'வாகனத்தை புதுப்பி',
    'Vehicle Already Exists': 'வாகனம் ஏற்கனவே உள்ளது',
    'No records available for export.': 'ஏற்றுமதி செய்ய பதிவுகள் இல்லை.',
    'No report data available to export.': 'ஏற்றுமதி செய்ய அறிக்கை தரவு இல்லை.',
    'No report data available to print.': 'அச்சிட அறிக்கை தரவு இல்லை.',
    'No inventory stock records found.':
        'சரக்கு இருப்பு பதிவுகள் எதுவும் இல்லை.',
    'No purchase records found for the selected filters.':
        'தேர்ந்தெடுத்த வடிகட்டிகளுக்கு கொள்முதல் பதிவுகள் இல்லை.',
    'No purchase records found for the selected period.':
        'தேர்ந்தெடுத்த காலத்திற்கு கொள்முதல் பதிவுகள் இல்லை.',
    'No spare usage records found.': 'உதிரி பாக பயன்பாட்டு பதிவுகள் இல்லை.',
    'No stock movements recorded yet.':
        'இன்னும் இருப்பு நகர்வு பதிவுகள் இல்லை.',
    'No diesel filling records yet.': 'இன்னும் டீசல் நிரப்பல் பதிவுகள் இல்லை.',
    'No diesel filling recorded for this period.':
        'இந்த காலத்திற்கு டீசல் நிரப்பல் பதிவு இல்லை.',
    'No vehicle consumption recorded for this period.':
        'இந்த காலத்திற்கு வாகன பயன்பாடு பதிவு இல்லை.',
    'No blasting material purchases recorded yet.':
        'இன்னும் பிளாஸ்டிங் பொருள் கொள்முதல் பதிவுகள் இல்லை.',
    'No compliance data available to export.':
        'ஏற்றுமதி செய்ய இணக்கப்பாட்டு தரவு இல்லை.',
    'No service items detected.': 'சேவை பொருட்கள் கண்டறியப்படவில்லை.',
    'No items extracted. Add items after OCR.':
        'பொருட்கள் பிரித்தெடுக்கப்படவில்லை. OCR பிறகு பொருட்களைச் சேர்க்கவும்.',
    'Not detected': 'கண்டறியப்படவில்லை',
    'Not Configured': 'உள்ளமைக்கப்படவில்லை',
    'Valid': 'செல்லுபடியாகும்',
    'Due Soon': 'விரைவில் காலாவதியாகும்',
    'Expired': 'காலாவதியானது',
    'Delete Excavator?': 'எக்ஸ்கவேட்டரை நீக்கவா?',
    'Delete Maintenance Record?': 'பராமரிப்பு பதிவை நீக்கவா?',
    'Delete Purchase?': 'கொள்முதலை நீக்கவா?',
    'Delete Service?': 'சேவை பதிவை நீக்கவா?',
    'Delete Vehicle?': 'வாகனத்தை நீக்கவா?',
    'This purchase record will be permanently deleted. This action cannot be undone.':
        'இந்த கொள்முதல் பதிவு நிரந்தரமாக நீக்கப்படும். இந்த செயலை மீண்டும் மாற்ற முடியாது.',
    'Diesel filling saved successfully.':
        'டீசல் நிரப்பல் வெற்றிகரமாக சேமிக்கப்பட்டது.',
    'Diesel receipt added and stock updated.':
        'டீசல் ரசீது சேர்க்கப்பட்டு இருப்பு புதுப்பிக்கப்பட்டது.',
    'Spare usage recorded.': 'உதிரி பாக பயன்பாடு பதிவு செய்யப்பட்டது.',
    'Purchase deleted successfully.': 'கொள்முதல் வெற்றிகரமாக நீக்கப்பட்டது.',
    'Enter a valid source, quantity and rate.':
        'சரியான மூலம், அளவு மற்றும் விலையை உள்ளிடவும்.',
    'Verifying RC...': 'RC சரிபார்க்கப்படுகிறது...',
    'Export failed: ': 'ஏற்றுமதி தோல்வியடைந்தது: ',
    'Excel export failed: ': 'Excel ஏற்றுமதி தோல்வியடைந்தது: ',
    'PDF export failed: ': 'PDF ஏற்றுமதி தோல்வியடைந்தது: ',
    'Print failed: ': 'அச்சிடுதல் தோல்வியடைந்தது: ',
    'Failed to extract data: ': 'தரவைப் பிரித்தெடுக்க முடியவில்லை: ',
    'Failed to extract service data: ':
        'சேவை தரவைப் பிரித்தெடுக்க முடியவில்லை: ',
    'Export Compliance Report': 'இணக்கப்பாட்டு அறிக்கையை ஏற்றுமதி செய்',
    'From Date': 'தொடக்க தேதி',
    'To Date': 'முடிவு தேதி',
    'DATE': 'தேதி',
    'Excel exported successfully.\\n':
        'Excel வெற்றிகரமாக ஏற்றுமதி செய்யப்பட்டது.\\n',
    'Filling Details': 'நிரப்பல் விவரங்கள்',
    'Vehicle Type': 'வாகன வகை',
    'Recent Filling History': 'சமீபத்திய நிரப்பல் வரலாறு',
    'Diesel Reports': 'டீசல் அறிக்கைகள்',
    'Diesel Received': 'பெற்ற டீசல்',
    'Average Rate': 'சராசரி விலை',
    'Per litre': 'ஒரு லிட்டருக்கு',
    'Diesel Filling Report': 'டீசல் நிரப்பல் அறிக்கை',
    'Vehicle Consumption': 'வாகன டீசல் பயன்பாடு',
    'Selected period': 'தேர்ந்தெடுத்த காலம்',
    'Track diesel received, used and current balance.':
        'பெறப்பட்ட, பயன்படுத்திய மற்றும் தற்போதைய டீசல் இருப்பை கண்காணிக்கவும்.',
    'Opening Stock': 'தொடக்க இருப்பு',
    'Current stock': 'தற்போதைய இருப்பு',
    'Live balance': 'தற்போதைய இருப்பு',
    'Receipt Date': 'ரசீது தேதி',
    'Diesel Management': 'டீசல் மேலாண்மை',
    'Available Diesel': 'கிடைக்கும் டீசல்',
    'Total Diesel Cost': 'மொத்த டீசல் செலவு',
    'Compliance Type': 'இணக்கப்பாட்டு வகை',
    'Compliance Report': 'இணக்கப்பாட்டு அறிக்கை',
    'Mandatory RTO Compliance': 'கட்டாய RTO இணக்கப்பாடு',
    '30-Day Automated Warning': '30 நாள் தானியங்கி எச்சரிக்கை',
    'Document Archival': 'ஆவண காப்பகம்',
    'Search registration, manufacturer or model':
        'பதிவு எண், உற்பத்தியாளர் அல்லது மாடலைத் தேடுக',
    'Equipment Type': 'உபகரண வகை',
    'Compliance report exported successfully.\\n':
        'இணக்கப்பாட்டு அறிக்கை வெற்றிகரமாக ஏற்றுமதி செய்யப்பட்டது.\\n',
    'Compliance export failed: ': 'இணக்கப்பாட்டு ஏற்றுமதி தோல்வியடைந்தது: ',
    'Enter username': 'பயனர்பெயரை உள்ளிடவும்',
    'Enter password': 'கடவுச்சொல்லை உள்ளிடவும்',
    'Bullet Qty': 'புல்லெட் அளவு',
    '3m Wire Qty': '3 மீட்டர் கம்பி அளவு',
    '4m Wire Qty': '4 மீட்டர் கம்பி அளவு',
    'ED Qty': 'ED அளவு',
    'Purchase Records': 'கொள்முதல் பதிவுகள்',
    'Purchase Date': 'கொள்முதல் தேதி',
    'Purchase Items': 'கொள்முதல் பொருட்கள்',
    'Purchase Reports': 'கொள்முதல் அறிக்கைகள்',
    'Report Filters': 'அறிக்கை வடிகட்டிகள்',
    'Report Period': 'அறிக்கை காலம்',
    'Period Summary': 'கால சுருக்கம்',
    'Purchase Records in Selected Period':
        'தேர்ந்தெடுத்த காலத்திற்கான கொள்முதல் பதிவுகள்',
    'Quarry Blasting Purchase': 'குவாரி பிளாஸ்டிங் கொள்முதல்',
    'Total Purchases': 'மொத்த கொள்முதல்கள்',
    'Bullet Quantity': 'புல்லெட் அளவு',
    'Total Wire Quantity': 'மொத்த கம்பி அளவு',
    'Total Purchase Cost': 'மொத்த கொள்முதல் செலவு',
    'Purchase Cost Summary': 'கொள்முதல் செலவு சுருக்கம்',
    'Recent Purchase History': 'சமீபத்திய கொள்முதல் வரலாறு',
    'View Purchase History': 'கொள்முதல் வரலாற்றைப் பார்',
    'OVERDUE': 'காலதாமதம்',
    'Immediate attention required': 'உடனடி கவனம் தேவை',
    'DUE NOW': 'இப்போது செய்ய வேண்டியது',
    'Service is due': 'சேவை செய்ய வேண்டியுள்ளது',
    'UPCOMING': 'வரவிருக்கும்',
    'Within warning threshold': 'எச்சரிக்கை வரம்பிற்குள் உள்ளது',
    'NOT RECORDED': 'பதிவு செய்யப்படவில்லை',
    'No service history': 'சேவை வரலாறு இல்லை',
    'Search registration, model or spare...':
        'பதிவு எண், மாடல் அல்லது உதிரி பாகத்தைத் தேடுக',
    'Overdue': 'காலதாமதம்',
    'Upcoming': 'வரவிருக்கும்',
    'Not Recorded': 'பதிவு செய்யப்படவில்லை',
    'View All': 'அனைத்தையும் பார்',
    'Total Excavators': 'மொத்த எக்ஸ்கவேட்டர்கள்',
    'working': 'செயல்பாட்டில்',
    'Transport Vehicles': 'போக்குவரத்து வாகனங்கள்',
    'Working Hours': 'பணி நேரம்',
    'Today': 'இன்று',
    'Transport KM': 'போக்குவரத்து கி.மீ.',
    'Diesel Expense': 'டீசல் செலவு',
    'Today\'s Excavator Operations': 'இன்றைய எக்ஸ்கவேட்டர் செயல்பாடுகள்',
    'Service Overview': 'சேவை மேலோட்டம்',
    'Today\'s Transport Operations': 'இன்றைய போக்குவரத்து செயல்பாடுகள்',
    'Recent Service Activity': 'சமீபத்திய சேவை நடவடிக்கைகள்',
    'Tonnage': 'டன்னேஜ்',
    'Loads': 'சுமைகள்',
    'Loading Site': 'ஏற்றுமிடம்',
    'Unloading Site': 'இறக்குமிடம்',
    'Total Items': 'மொத்த பொருட்கள்',
    'Purchased Qty': 'வாங்கிய அளவு',
    'Used Qty': 'பயன்படுத்திய அளவு',
    'Remaining': 'மீதம்',
    'Search spare item...': 'உதிரி பாகத்தைத் தேடுக...',
    'Purchase Cost': 'கொள்முதல் செலவு',
    'Spare Item': 'உதிரி பாகம்',
    'Upload Spare Purchase Bill': 'உதிரி பாக கொள்முதல் பில்லை பதிவேற்று',
    'Review Purchase Details': 'கொள்முதல் விவரங்களை சரிபார்',
    'Spare Inventory': 'உதிரி பாக இருப்பு',
    'Total Spare Items': 'மொத்த உதிரி பாகங்கள்',
    'Purchased Quantity': 'வாங்கிய அளவு',
    'Used Quantity': 'பயன்படுத்திய அளவு',
    'Remaining Stock': 'மீதமுள்ள இருப்பு',
    'Total Used Quantity': 'மொத்த பயன்பாட்டு அளவு',
    'Usage History': 'பயன்பாட்டு வரலாறு',
    'Machine Details': 'இயந்திர விவரங்கள்',
    'Search Machine': 'இயந்திரத்தைத் தேடுக',
    'Check registration': 'பதிவு எண்ணைச் சரிபார்',
    'Excavator Details': 'எக்ஸ்கவேட்டர் விவரங்கள்',
    'Registration Number': 'பதிவு எண்',
    'Excavator Model': 'எக்ஸ்கவேட்டர் மாடல்',
    'Manufacturing Year': 'உற்பத்தி ஆண்டு',
    'Owner Name': 'உரிமையாளர் பெயர்',
    'Color': 'நிறம்',
    'Permanent Address': 'நிரந்தர முகவரி',
    'Vehicle Chasi Number': 'வாகன சேஸி எண்',
    'Vehicle Engine Number': 'வாகன இன்ஜின் எண்',
    'Insurance Company': 'காப்பீட்டு நிறுவனம்',
    'Vehicle Compliance': 'வாகன இணக்கப்பாடு',
    'Insurance Expiry': 'காப்பீடு காலாவதி',
    'FC Expiry': 'FC காலாவதி',
    'Permit Expiry': 'அனுமதி காலாவதி',
    'Tax Expiry': 'வரி காலாவதி',
    'Clear date': 'தேதியை அழி',
    'Total Working Hour': 'மொத்த பணி நேரம்',
    'Total Running Hour': 'மொத்த இயக்க நேரம்',
    'Starting Hour': 'தொடக்க மணி',
    'Closing Hour': 'முடிவு மணி',
    'Bucket Working Hour': 'பக்கெட் பணி நேரம்',
    'Breaker Working Hour': 'பிரேக்கர் பணி நேரம்',
    'Production': 'உற்பத்தி',
    'Units': 'அலகுகள்',
    'Diesel Filled (L)': 'நிரப்பிய டீசல் (லிட்டர்)',
    'Diesel Consumption (L/KM)': 'டீசல் பயன்பாடு (லிட்டர்/கி.மீ.)',
    'Excavator ID': 'எக்ஸ்கவேட்டர் ID',
    'Operation Details': 'செயல்பாட்டு விவரங்கள்',
    'Operator Name': 'ஆபரேட்டர் பெயர்',
    'Images': 'படங்கள்',
    'Total Services': 'மொத்த சேவைகள்',
    'This Month': 'இந்த மாதம்',
    'Active Excavators': 'செயலில் உள்ள எக்ஸ்கவேட்டர்கள்',
    'Search registration number, date or remarks...':
        'பதிவு எண், தேதி அல்லது குறிப்புகளைத் தேடுக...',
    'SERVICE DATE': 'சேவை தேதி',
    'Service Details': 'சேவை விவரங்கள்',
    'Excavator Registration': 'எக்ஸ்கவேட்டர் பதிவு எண்',
    'Service Date': 'சேவை தேதி',
    'Current Hour Meter': 'தற்போதைய மணி மீட்டர்',
    'Service Items': 'சேவை பொருட்கள்',
    'Spare Part': 'உதிரி பாகம்',
    'Cost / Unit': 'ஒரு அலகின் விலை',
    'Item Remark': 'பொருள் குறிப்பு',
    'Remove': 'நீக்கு',
    'Service Remarks': 'சேவை குறிப்புகள்',
    'Vehicle Details': 'வாகன விவரங்கள்',
    'Vehicle Model': 'வாகன மாடல்',
    'Emission Standard': 'மாசு உமிழ்வு தரநிலை',
    'Compliance Documents': 'இணக்கப்பாட்டு ஆவணங்கள்',
    'Vehicle & Driver': 'வாகனம் & ஓட்டுநர்',
    'Kilometer Reading': 'கிலோமீட்டர் அளவீடு',
    'Starting KM': 'தொடக்க கி.மீ.',
    'Trip & Load Details': 'பயணம் & சுமை விவரங்கள்',
    'Number of Loads': 'சுமைகளின் எண்ணிக்கை',
    'Diesel & Fuel': 'டீசல் & எரிபொருள்',
    'Diesel Filled': 'நிரப்பிய டீசல்',
    'Active Vehicles': 'செயலில் உள்ள வாகனங்கள்',
    'CURRENT KM': 'தற்போதைய கி.மீ.',
    'Transport Registration': 'போக்குவரத்து பதிவு எண்',
    'Global Search...': 'தேடுக...',
    'Next': 'அடுத்து',
    'Back': 'பின் செல்',
    'Bills': 'பில்கள்',
    'Diesel Stock': 'டீசல் இருப்பு',
    'Diesel Filling': 'டீசல் நிரப்பல்',
    'Vehicles': 'வாகனங்கள்',
    'Diesel Consumption': 'டீசல் பயன்பாடு',
    'Optional': 'விருப்பம்',
    'Enter any additional service notes...':
        'கூடுதல் சேவை குறிப்புகளை உள்ளிடவும்...',
    'Select vehicle': 'வாகனத்தைத் தேர்ந்தெடுக்கவும்',
    'Enter loading location': 'ஏற்றுமிடத்தை உள்ளிடவும்',
    'Enter unloading location': 'இறக்குமிடத்தை உள்ளிடவும்',
    'Enter additional notes or observations':
        'கூடுதல் குறிப்புகள் அல்லது கவனிப்புகளை உள்ளிடவும்',
    'Search operator, excavator ID or remarks...':
        'ஆபரேட்டர், எக்ஸ்கவேட்டர் ID அல்லது குறிப்புகளைத் தேடுக...',
    'Manufacturer': 'உற்பத்தியாளர்',
    'Example: Tata': 'உதாரணம்: Tata',
    'Example: Prima': 'உதாரணம்: Prima',
    'Example: BS6': 'உதாரணம்: BS6',
    'Vehicle owner name': 'வாகன உரிமையாளர் பெயர்',
    'Permanent address': 'நிரந்தர முகவரி',
    'Chassis number': 'சேஸி எண்',
    'Engine number': 'இன்ஜின் எண்',
    'Vehicle color': 'வாகன நிறம்',
    'Insurance company': 'காப்பீட்டு நிறுவனம்',
    'Diesel Cost (₹/hr)': 'டீசல் செலவு (₹/மணி)',
    'Example: 1': 'உதாரணம்: 1',
    'Example: Tata Hitachi': 'உதாரணம்: Tata Hitachi',
    'Example: EX 210': 'உதாரணம்: EX 210',
    'Example: Yellow': 'உதாரணம்: Yellow',
    'Owner permanent address': 'உரிமையாளரின் நிரந்தர முகவரி',
    'Example: ICICI Lombard': 'உதாரணம்: ICICI Lombard',
    'Quantity Used': 'பயன்படுத்திய அளவு',
    'Recent Purchases': 'சமீபத்திய கொள்முதல்கள்',
    'Recent Spare Usage': 'சமீபத்திய உதிரி பாக பயன்பாடு',
    'Inventory Report': 'சரக்கு அறிக்கை',
    'Excel exported: ': 'Excel ஏற்றுமதி செய்யப்பட்டது: ',
    'Excel report saved: ': 'Excel அறிக்கை சேமிக்கப்பட்டது: ',
    'Due': 'செய்ய வேண்டியது',
    'Previous': 'முந்தைய',
    'FC': 'FC',
    'Filters': 'வடிகட்டிகள்',
    'Status': 'நிலை',
    'Equipment': 'உபகரணம்',
    'METER': 'மீட்டர்',
    'DETAILS': 'விவரங்கள்',
    'ITEMS': 'பொருட்கள்',
    'ACTION': 'செயல்',
    'Active Excavator': 'செயலில் உள்ள எக்ஸ்கவேட்டர்',
    'Active Vehicle': 'செயலில் உள்ள வாகனம்',
    'Add a vehicle to your fleet.':
        'உங்கள் வாகனப் பட்டியலில் ஒரு வாகனத்தைச் சேர்க்கவும்.',
    'Add an excavator to your fleet.':
        'உங்கள் எக்ஸ்கவேட்டர் பட்டியலில் ஒரு எக்ஸ்கவேட்டரைச் சேர்க்கவும்.',
    'Add your first excavator maintenance record to get started.':
        'தொடங்க உங்கள் முதல் எக்ஸ்கவேட்டர் பராமரிப்பு பதிவைச் சேர்க்கவும்.',
    'Add your first transport maintenance record to get started.':
        'தொடங்க உங்கள் முதல் போக்குவரத்து பராமரிப்பு பதிவைச் சேர்க்கவும்.',
    'Admin': 'நிர்வாகி',
    'All scheduled services are currently up to date.':
        'அனைத்து திட்டமிடப்பட்ட சேவைகளும் தற்போது சரியான நிலையில் உள்ளன.',
    'Analyzing the uploaded sheet': 'பதிவேற்றிய ஷீட்டை பகுப்பாய்வு செய்கிறது',
    'Are you sure you want to delete this excavator?':
        'இந்த எக்ஸ்கவேட்டரை நீக்க விரும்புகிறீர்களா?',
    'Are you sure you want to delete this transport vehicle?':
        'இந்த போக்குவரத்து வாகனத்தை நீக்க விரும்புகிறீர்களா?',
    'Are you sure you want to delete the service record':
        'இந்த சேவை பதிவை நீக்க விரும்புகிறீர்களா?',
    'Compliance Overview': 'இணக்கப்பாட்டு மேலோட்டம்',
    'Excavator Master': 'எக்ஸ்கவேட்டர் முதன்மை',
    'Extracting Data...': 'தரவைப் பிரித்தெடுக்கிறது...',
    'Manage registered excavators across the fleet.':
        'பட்டியலில் உள்ள அனைத்து எக்ஸ்கவேட்டர்களையும் நிர்வகிக்கவும்.',
    'Manage registered transport vehicles across the fleet.':
        'பட்டியலில் உள்ள அனைத்து போக்குவரத்து வாகனங்களையும் நிர்வகிக்கவும்.',
    'Management System': 'மேலாண்மை அமைப்பு',
    'Mark if the excavator teeth set was changed':
        'எக்ஸ்கவேட்டர் பற்கள் தொகுப்பு மாற்றப்பட்டிருந்தால் குறிக்கவும்',
    'Monitor insurance, FC, permit and tax expiry status across your fleet.':
        'உங்கள் வாகனப் பட்டியலின் காப்பீடு, FC, அனுமதி மற்றும் வரி காலாவதி நிலையை கண்காணிக்கவும்.',
    'Monitor upcoming and overdue service requirements':
        'வரவிருக்கும் மற்றும் காலதாமதமான சேவை தேவைகளை கண்காணிக்கவும்',
    'No compliance records found': 'இணக்கப்பாட்டு பதிவுகள் எதுவும் இல்லை',
    'No diesel consumption recorded for this period.':
        'இந்த காலத்திற்கு டீசல் பயன்பாடு பதிவு செய்யப்படவில்லை.',
    'No excavators found': 'எக்ஸ்கவேட்டர்கள் எதுவும் இல்லை',
    'No maintenance records found': 'பராமரிப்பு பதிவுகள் எதுவும் இல்லை',
    'No records found for the selected filters.':
        'தேர்ந்தெடுத்த வடிகட்டிகளுக்கு பதிவுகள் எதுவும் இல்லை.',
    'No report records found': 'அறிக்கை பதிவுகள் எதுவும் இல்லை',
    'No service notifications': 'சேவை அறிவிப்புகள் எதுவும் இல்லை',
    'No spare parts added': 'உதிரி பாகங்கள் எதுவும் சேர்க்கப்படவில்லை',
    'No transport vehicles found': 'போக்குவரத்து வாகனங்கள் எதுவும் இல்லை',
    'Overview of your fleet operations':
        'உங்கள் வாகனப் பட்டியல் செயல்பாடுகளின் மேலோட்டம்',
    'Password': 'கடவுச்சொல்',
    'Rows per page': 'ஒரு பக்கத்திற்கான வரிசைகள்',
    'SIGN IN': 'உள்நுழைக',
    'Secure access for authorized users':
        'அங்கீகரிக்கப்பட்ட பயனர்களுக்கான பாதுகாப்பான அணுகல்',
    'Select an excavator to view details':
        'விவரங்களைப் பார்க்க எக்ஸ்கவேட்டரைத் தேர்ந்தெடுக்கவும்',
    'Sign in to continue to your dashboard': 'டாஷ்போர்டைத் தொடர உள்நுழைக',
    'Spare parts used during this service':
        'இந்த சேவையில் பயன்படுத்திய உதிரி பாகங்கள்',
    'TOTAL': 'மொத்தம்',
    'Teeth Set Changed': 'பற்கள் தொகுப்பு மாற்றப்பட்டது',
    'This maintenance record will be permanently deleted. This action cannot be undone.':
        'இந்த பராமரிப்பு பதிவு நிரந்தரமாக நீக்கப்படும். இந்த செயலை மீண்டும் மாற்ற முடியாது.',
    'Total Service Cost': 'மொத்த சேவை செலவு',
    'Track daily excavator operation, fuel usage and maintenance activities.':
        'தினசரி எக்ஸ்கவேட்டர் இயக்கம், எரிபொருள் பயன்பாடு மற்றும் பராமரிப்பு நடவடிக்கைகளைப் பதிவு செய்யவும்.',
    'Track daily transport vehicle operation, fuel usage and maintenance activities.':
        'தினசரி போக்குவரத்து வாகன இயக்கம், எரிபொருள் பயன்பாடு மற்றும் பராமரிப்பு நடவடிக்கைகளைப் பதிவு செய்யவும்.',
    'Track excavator servicing, spare parts and service history.':
        'எக்ஸ்கவேட்டர் சேவை, உதிரி பாகங்கள் மற்றும் சேவை வரலாற்றைக் கண்காணிக்கவும்.',
    'Track expiry status for all registered assets.':
        'அனைத்து பதிவு செய்யப்பட்ட சொத்துகளின் காலாவதி நிலையை கண்காணிக்கவும்.',
    'Track transport vehicle servicing, spare parts and service history.':
        'போக்குவரத்து வாகன சேவை, உதிரி பாகங்கள் மற்றும் சேவை வரலாற்றைக் கண்காணிக்கவும்.',
    'Transport Master': 'போக்குவரத்து முதன்மை',
    'Try changing the report type, equipment or date filters.':
        'அறிக்கை வகை, உபகரணம் அல்லது தேதி வடிகட்டிகளை மாற்றிப் பார்க்கவும்.',
    'Try changing your filters or add compliance information.':
        'வடிகட்டிகளை மாற்றவும் அல்லது இணக்கப்பாட்டு தகவலைச் சேர்க்கவும்.',
    'Unable to load compliance data': 'இணக்கப்பாட்டு தரவை ஏற்ற முடியவில்லை',
    'Unable to load dashboard': 'டாஷ்போர்டை ஏற்ற முடியவில்லை',
    'Unable to load excavators': 'எக்ஸ்கவேட்டர் தரவை ஏற்ற முடியவில்லை',
    'Unable to load maintenance records':
        'பராமரிப்பு பதிவுகளை ஏற்ற முடியவில்லை',
    'Unable to load report': 'அறிக்கையை ஏற்ற முடியவில்லை',
    'Unable to load service notifications':
        'சேவை அறிவிப்புகளை ஏற்ற முடியவில்லை',
    'Unable to load service records': 'சேவை பதிவுகளை ஏற்ற முடியவில்லை',
    'Unable to load transport vehicles':
        'போக்குவரத்து வாகன தரவை ஏற்ற முடியவில்லை',
    'Upload a photo of the purchase bill':
        'கொள்முதல் பில்லின் புகைப்படத்தை பதிவேற்றவும்',
    'Username': 'பயனர்பெயர்',
    'View maintenance and service reports for excavators and transport vehicles.':
        'எக்ஸ்கவேட்டர் மற்றும் போக்குவரத்து வாகனங்களின் பராமரிப்பு மற்றும் சேவை அறிக்கைகளைப் பார்க்கவும்.',
    'Welcome back': 'மீண்டும் வரவேற்கிறோம்',
    '3m Wire Price': '3 மீட்டர் கம்பி விலை',
    '4m Wire Price': '4 மீட்டர் கம்பி விலை',
    'Bullet Price': 'புல்லெட் விலை',
    'COMPLIANCE': 'இணக்கப்பாடு',
    'COST': 'செலவு',
    'ED Price': 'ED விலை',
    'LAST PURCHASE': 'கடைசி கொள்முதல்',
    'Night': 'இரவு',
    'REMARKS': 'குறிப்புகள்',
    'STATUS': 'நிலை',
    'Type': 'வகை',
    'English': 'English',
    'Save Service': 'சேவையை சேமி',
    'Save Maintenance': 'பராமரிப்பை சேமி',
    'Save Vehicle': 'வாகனத்தை சேமி',
    'Save Excavator': 'எக்ஸ்கவேட்டரை சேமி',
    'Save Purchase': 'கொள்முதலை சேமி',
    'Extract Data': 'தரவைப் பிரித்தெடு',
    'Extract': 'பிரித்தெடு',
    'Add Purchase': 'கொள்முதலை சேர்',
    'Generate Report': 'அறிக்கையை உருவாக்கு',
    'Reset': 'மீட்டமை',
    'Apply': 'பயன்படுத்து',
    'Notifications': 'அறிவிப்புகள்',
    'notifications': 'அறிவிப்புகள்',
    'Requiring Attention': 'கவனம் தேவை',
    '0 Requiring Attention': 'கவனம் தேவை: 0',
    'Search registration number, date, remarks...':
        'பதிவு எண், தேதி அல்லது குறிப்புகளைத் தேடுக...',
    'Search driver, vehicle ID, loading or unloading site...':
        'ஓட்டுநர், வாகன எண், ஏற்றுமிடம் அல்லது இறக்குமிடத்தைத் தேடுக...',
    'Search spare item, used for, remarks...':
        'உதிரி பாகம், பயன்படுத்திய நோக்கம் அல்லது குறிப்புகளைத் தேடுக...',
    'No service records found': 'சேவை பதிவுகள் எதுவும் இல்லை',
    'Add your first transport service record to get started.':
        'தொடங்க உங்கள் முதல் போக்குவரத்து சேவை பதிவைச் சேர்க்கவும்.',
    'Add your first excavator service record to get started.':
        'தொடங்க உங்கள் முதல் எக்ஸ்கவேட்டர் சேவை பதிவைச் சேர்க்கவும்.',
    'No transport operations recorded today.':
        'இன்று எந்த போக்குவரத்து செயல்பாடுகளும் பதிவு செய்யப்படவில்லை.',
    'No excavator operations recorded today.':
        'இன்று எந்த எக்ஸ்கவேட்டர் செயல்பாடுகளும் பதிவு செய்யப்படவில்லை.',
    'No service records available.': 'சேவை பதிவுகள் எதுவும் கிடைக்கவில்லை.',
    'No recent service activity.': 'சமீபத்திய சேவை நடவடிக்கைகள் எதுவும் இல்லை.',
    'No spare purchases recorded yet.':
        'இன்னும் உதிரி பாக கொள்முதல் பதிவுகள் இல்லை.',
    'No spare usage recorded yet.':
        'இன்னும் உதிரி பாக பயன்பாட்டு பதிவுகள் இல்லை.',
    'No records available.': 'பதிவுகள் எதுவும் கிடைக்கவில்லை.',
    'No records found.': 'பதிவுகள் எதுவும் கிடைக்கவில்லை.',
    'No notifications': 'அறிவிப்புகள் எதுவும் இல்லை',
    'This excavator is currently active.':
        'இந்த எக்ஸ்கவேட்டர் தற்போது செயல்பாட்டில் உள்ளது.',
    'This vehicle is currently active.':
        'இந்த வாகனம் தற்போது செயல்பாட்டில் உள்ளது.',
    'Verify RC Details': 'RC விவரங்களைச் சரிபார்',
    'Add Transport Maintenance': 'போக்குவரத்து பராமரிப்பை சேர்',
    'Add Transport Service': 'போக்குவரத்து சேவையை சேர்',
    'Add Transport Vehicle': 'போக்குவரத்து வாகனத்தை சேர்',
    'Click "Add Spare" to add a service item.':
        'சேவை பொருளைச் சேர்க்க "உதிரி பாகத்தை சேர்" என்பதை அழுத்தவும்.',
    'Record excavator service details and spare parts used.':
        'எக்ஸ்கவேட்டர் சேவை விவரங்கள் மற்றும் பயன்படுத்திய உதிரி பாகங்களைப் பதிவு செய்யவும்.',
    'Record transport vehicle service details and spare parts used.':
        'போக்குவரத்து வாகன சேவை விவரங்கள் மற்றும் பயன்படுத்திய உதிரி பாகங்களைப் பதிவு செய்யவும்.',
    'Record daily excavator maintenance details':
        'தினசரி எக்ஸ்கவேட்டர் பராமரிப்பு விவரங்களைப் பதிவு செய்யவும்',
    'Record daily transport vehicle operation and maintenance details.':
        'தினசரி போக்குவரத்து வாகன இயக்கம் மற்றும் பராமரிப்பு விவரங்களைப் பதிவு செய்யவும்.',
    'Register a new excavator in the fleet.':
        'வாகனப் பட்டியலில் புதிய எக்ஸ்கவேட்டரைப் பதிவு செய்யவும்.',
    'Register a new transport vehicle in the fleet.':
        'வாகனப் பட்டியலில் புதிய போக்குவரத்து வாகனத்தைப் பதிவு செய்யவும்.',
    'Enter quantities and unit prices for the four fixed blasting items.':
        'நான்கு நிர்ணயிக்கப்பட்ட பிளாஸ்டிங் பொருட்களுக்கான அளவு மற்றும் அலகு விலையை உள்ளிடவும்.',
    'Track blasting material purchases and purchase costs.':
        'பிளாஸ்டிங் பொருட்களின் கொள்முதல் மற்றும் கொள்முதல் செலவுகளைக் கண்காணிக்கவும்.',
    'View and filter all quarry blasting material purchase records.':
        'அனைத்து குவாரி பிளாஸ்டிங் பொருள் கொள்முதல் பதிவுகளையும் பார்க்கவும் மற்றும் வடிகட்டவும்.',
    'Generate daily, weekly, monthly and yearly blasting material reports.':
        'தினசரி, வாராந்திர, மாதாந்திர மற்றும் வருடாந்திர பிளாஸ்டிங் பொருள் அறிக்கைகளை உருவாக்கவும்.',
    'Generate daily, weekly, monthly and yearly spare inventory reports.':
        'தினசரி, வாராந்திர, மாதாந்திர மற்றும் வருடாந்திர உதிரி பாக இருப்பு அறிக்கைகளை உருவாக்கவும்.',
    'Manage spare purchases, stock usage and inventory reports.':
        'உதிரி பாக கொள்முதல், இருப்பு பயன்பாடு மற்றும் இருப்பு அறிக்கைகளை நிர்வகிக்கவும்.',
    'Upload a purchase bill, extract data and verify it before saving.':
        'கொள்முதல் பில்லை பதிவேற்றி, தரவைப் பிரித்தெடுத்து, சேமிப்பதற்கு முன் சரிபார்க்கவும்.',
    'Bill Number': 'பில் எண்',
    'Supplier Name': 'சப்ளையர் பெயர்',
    'Purchase Date (YYYY-MM-DD)': 'கொள்முதல் தேதி (YYYY-MM-DD)',
    'Subtotal': 'கூட்டுத்தொகை',
    'GST Amount': 'GST தொகை',
    'Grand Total': 'மொத்த இறுதி தொகை',
    'Purchase saved successfully.': 'கொள்முதல் வெற்றிகரமாக சேமிக்கப்பட்டது.',
    'Bill data extracted. Please review before saving.':
        'பில் தரவு பிரித்தெடுக்கப்பட்டது. சேமிப்பதற்கு முன் சரிபார்க்கவும்.',
    'Add at least one purchase item.':
        'குறைந்தது ஒரு கொள்முதல் பொருளையாவது சேர்க்கவும்.',
    'Available Stock': 'கிடைக்கும் இருப்பு',
    'Shift (Optional)': 'ஷிப்ட் (விருப்பம்)',
    'Select excavator': 'எக்ஸ்கவேட்டரைத் தேர்ந்தெடுக்கவும்',
    'Select service date': 'சேவை தேதியைத் தேர்ந்தெடுக்கவும்',
    'Select spare': 'உதிரி பாகத்தைத் தேர்ந்தெடுக்கவும்',
    'Select transport vehicle': 'போக்குவரத்து வாகனத்தைத் தேர்ந்தெடுக்கவும்',
    'Select a spare item': 'ஒரு உதிரி பாகத்தைத் தேர்ந்தெடுக்கவும்',
    'Diesel Lorry': 'டீசல் லாரி',
    'Compare diesel consumption and cost vehicle by vehicle.':
        'ஒவ்வொரு வாகனத்திற்குமான டீசல் பயன்பாடு மற்றும் செலவை ஒப்பிடவும்.',
    'Generate daily, weekly, monthly and custom diesel reports.':
        'தினசரி, வாராந்திர, மாதாந்திர மற்றும் தனிப்பயன் டீசல் அறிக்கைகளை உருவாக்கவும்.',
    'Track diesel stock, vehicle consumption and fuel expenses.':
        'டீசல் இருப்பு, வாகன பயன்பாடு மற்றும் எரிபொருள் செலவுகளைக் கண்காணிக்கவும்.',
    'Track purchased, used and remaining quantities for each spare.':
        'ஒவ்வொரு உதிரி பாகத்திற்கும் வாங்கிய, பயன்படுத்திய மற்றும் மீதமுள்ள அளவைக் கண்காணிக்கவும்.',
    'Show password': 'கடவுச்சொல்லைக் காட்டு',
    'No transport service records found':
        'போக்குவரத்து சேவை பதிவுகள் எதுவும் இல்லை',
    'No excavator service records found':
        'எக்ஸ்கவேட்டர் சேவை பதிவுகள் எதுவும் இல்லை',
    'No transport maintenance records found':
        'போக்குவரத்து பராமரிப்பு பதிவுகள் எதுவும் இல்லை',
    'No excavator maintenance records found':
        'எக்ஸ்கவேட்டர் பராமரிப்பு பதிவுகள் எதுவும் இல்லை',
    'Overall Status': 'மொத்த நிலை',
    'Filter': 'வடிகட்டி',
    'Used For (e.g. Excavator / Transport / Service)':
        'பயன்படுத்திய நோக்கம் (எ.கா. எக்ஸ்கவேட்டர் / போக்குவரத்து / சேவை)',
    'Service is due now': 'சேவை இப்போது செய்ய வேண்டியுள்ளது',
    'Service Not Recorded': 'சேவை பதிவு செய்யப்படவில்லை',
    'SERVICE DUE': 'சேவை செய்ய வேண்டியது',
    'SERVICE NOT RECORDED': 'சேவை பதிவு செய்யப்படவில்லை',
    'Model': 'மாடல்',
    'Assets': 'சொத்துகள்',
    'The registration number': 'பதிவு எண்',
    'is already registered in StoneFleet.':
        'StoneFleet-ல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.',
    'Please upload a bill first.': 'முதலில் ஒரு பில்லை பதிவேற்றவும்.',
    'Total Assets': 'மொத்த சொத்துகள்',
    'Please enter username': 'பயனர்பெயரை உள்ளிடவும்',
    'Please enter password': 'கடவுச்சொல்லை உள்ளிடவும்',
    'Hide password': 'கடவுச்சொல்லை மறை',
    'Keep insurance, FC, permit and tax information updated for every asset.':
        'ஒவ்வொரு சொத்திற்குமான காப்பீடு, FC, அனுமதி மற்றும் வரி தகவல்களைப் புதுப்பித்து வைத்திருக்கவும்.',
    'Assets approaching expiry within 30 days are marked as Due Soon.':
        '30 நாட்களுக்குள் காலாவதியாகும் சொத்துகள் "விரைவில் காலாவதியாகும்" எனக் குறிக்கப்படும்.',
    'Maintain accurate compliance dates for operational and audit reference.':
        'செயல்பாடு மற்றும் தணிக்கை பயன்பாட்டிற்கான சரியான இணக்கப்பாட்டு தேதிகளை பராமரிக்கவும்.',
    'Invalid username or password.': 'பயனர்பெயர் அல்லது கடவுச்சொல் தவறானது.',
    'Login failed. Please try again.':
        'உள்நுழைவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    'Enter quantity': 'அளவை உள்ளிடவும்',
    'Custom Range': 'தனிப்பயன் காலவரம்பு',
    'Change Bill': 'பில்லை மாற்று',
    'Update Purchase': 'கொள்முதலை புதுப்பி',
    'Update Maintenance': 'பராமரிப்பை புதுப்பி',
    'Update Service': 'சேவையை புதுப்பி',
    'Edit Maintenance': 'பராமரிப்பை திருத்து',
    'Update excavator maintenance details':
        'எக்ஸ்கவேட்டர் பராமரிப்பு விவரங்களை புதுப்பிக்கவும்',
    'Saving...': 'சேமிக்கப்படுகிறது...',
    'Edit Transport Maintenance': 'போக்குவரத்து பராமரிப்பை திருத்து',
    'Update transport maintenance record.':
        'போக்குவரத்து பராமரிப்பு பதிவை புதுப்பிக்கவும்',
    'Edit Excavator Service': 'எக்ஸ்கவேட்டர் சேவையை திருத்து',
    'Add Excavator Service': 'எக்ஸ்கவேட்டர் சேவையை சேர்',
    'Update service details and spare parts used.':
        'சேவை விவரங்கள் மற்றும் பயன்படுத்திய உதிரி பாகங்களை புதுப்பிக்கவும்',
    'Edit Transport Service': 'போக்குவரத்து சேவையை திருத்து',
    'Edit Excavator': 'எக்ஸ்கவேட்டரை திருத்து',
    'Update excavator details.': 'எக்ஸ்கவேட்டர் விவரங்களை புதுப்பிக்கவும்',
    'Edit Vehicle': 'வாகனத்தை திருத்து',
    'Update vehicle details.': 'வாகன விவரங்களை புதுப்பிக்கவும்',
    'Update registered excavator details.':
        'பதிவு செய்யப்பட்ட எக்ஸ்கவேட்டர் விவரங்களை புதுப்பிக்கவும்',
    'Update transport vehicle details.':
        'போக்குவரத்து வாகன விவரங்களை புதுப்பிக்கவும்',
    'Are you sure you want to delete the service record for':
        'இந்த சேவை பதிவை நீக்க விரும்புகிறீர்களா: ',
    'Click \\"Add Spare\\" to add a service item.':
        'சேவை பொருளைச் சேர்க்க "உதிரி பாகத்தை சேர்" என்பதை அழுத்தவும்.',

    'Record diesel filled from the diesel lorry into a vehicle.':
        'டீசல் லாரியிலிருந்து வாகனத்திற்கு நிரப்பிய டீசலைப் பதிவு செய்யவும்.',
    'Record spare parts consumed during maintenance and service.':
        'பராமரிப்பு மற்றும் சேவையில் பயன்படுத்திய உதிரி பாகங்களைப் பதிவு செய்யவும்.',
    'EXCAVATOR': 'எக்ஸ்கவேட்டர்',
    'TRANSPORT': 'போக்குவரத்து',
    'NORMAL': 'சாதாரணம்',
    'Current': 'தற்போதைய',
    'Excel exported successfully.': 'Excel வெற்றிகரமாக ஏற்றுமதி செய்யப்பட்டது.',
    'overdue': 'காலதாமதம்',
    'remaining': 'மீதமுள்ளது',
    'In Stock': 'இருப்பில் உள்ளது',
    'Out of Stock': 'இருப்பு இல்லை',
    'Low Stock': 'குறைந்த இருப்பு',
    'RECEIPT': 'ரசீது',
    'This Week': 'இந்த வாரம்',
    'Invalid': 'தவறான மதிப்பு',
    'Required': 'கட்டாயம்',
    'Enter a valid number': 'சரியான எண்ணை உள்ளிடவும்',
    'Enter registration number': 'பதிவு எண்ணை உள்ளிடவும்',
    'Registration number already exists': 'பதிவு எண் ஏற்கனவே உள்ளது',
    'Enter registration number first.': 'முதலில் பதிவு எண்ணை உள்ளிடவும்.',
    'RC verified successfully. Details auto-filled.':
        'RC வெற்றிகரமாக சரிபார்க்கப்பட்டது. விவரங்கள் தானாக நிரப்பப்பட்டன.',
    'Unable to verify RC:': 'RC-ஐ சரிபார்க்க முடியவில்லை',
    'Registration number is available.': 'பதிவு எண் கிடைக்கிறது.',
    'Unable to check registration: ': 'பதிவு எண்ணைச் சரிபார்க்க முடியவில்லை: ',
    'Enter manufacturer': 'உற்பத்தியாளரை உள்ளிடவும்',
    'Enter excavator model': 'எக்ஸ்கவேட்டர் மாடலை உள்ளிடவும்',
    'Enter vehicle model': 'வாகன மாடலை உள்ளிடவும்',
    'Enter manufacturing year': 'உற்பத்தி ஆண்டை உள்ளிடவும்',
    'Enter a valid year': 'சரியான ஆண்டை உள்ளிடவும்',
    'This excavator is currently inactive.':
        'இந்த எக்ஸ்கவேட்டர் தற்போது செயல்பாட்டில் இல்லை.',
    'This vehicle is currently inactive.':
        'இந்த வாகனம் தற்போது செயல்பாட்டில் இல்லை.',
    'Enter registration number.': 'பதிவு எண்ணை உள்ளிடவும்.',
    'Unable to save excavator.': 'எக்ஸ்கவேட்டரை சேமிக்க முடியவில்லை.',
    'Excavator updated successfully.':
        'எக்ஸ்கவேட்டர் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
    'Excavator added successfully.':
        'எக்ஸ்கவேட்டர் வெற்றிகரமாக சேர்க்கப்பட்டது.',
    'Unable to save transport vehicle.':
        'போக்குவரத்து வாகனத்தை சேமிக்க முடியவில்லை.',
    'Unable to save vehicle: ': 'வாகனத்தை சேமிக்க முடியவில்லை: ',
    'Transport vehicle updated successfully.':
        'போக்குவரத்து வாகனம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
    'Transport vehicle added successfully.':
        'போக்குவரத்து வாகனம் வெற்றிகரமாக சேர்க்கப்பட்டது.',
    'Enter current KM': 'தற்போதைய கி.மீ.யை உள்ளிடவும்',
    'Invalid KM': 'தவறான கி.மீ. மதிப்பு',
    'Enter hour meter': 'மணி மீட்டரை உள்ளிடவும்',
    'Invalid hour meter': 'தவறான மணி மீட்டர் மதிப்பு',
    'Please select an excavator.': 'எக்ஸ்கவேட்டரைத் தேர்ந்தெடுக்கவும்.',
    'Please select a transport vehicle.':
        'போக்குவரத்து வாகனத்தைத் தேர்ந்தெடுக்கவும்.',
    'Please add at least one spare part.':
        'குறைந்தது ஒரு உதிரி பாகத்தையாவது சேர்க்கவும்.',
    'Please select a spare part.': 'உதிரி பாகத்தைத் தேர்ந்தெடுக்கவும்.',
    'The same spare part cannot be added twice.':
        'ஒரே உதிரி பாகத்தை இரண்டு முறை சேர்க்க முடியாது.',
    'No active spare parts found. Please add spares first.':
        'செயலில் உள்ள உதிரி பாகங்கள் எதுவும் இல்லை. முதலில் உதிரி பாகங்களைச் சேர்க்கவும்.',
    'Unable to save service.': 'சேவையை சேமிக்க முடியவில்லை.',
    'Unable to update service.': 'சேவையை புதுப்பிக்க முடியவில்லை.',
    'Unable to update service items.':
        'சேவை பொருட்களை புதுப்பிக்க முடியவில்லை.',
    'Unable to save service item.': 'சேவை பொருளை சேமிக்க முடியவில்லை.',
    'Service updated successfully.': 'சேவை வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
    'Service added successfully.': 'சேவை வெற்றிகரமாக சேர்க்கப்பட்டது.',
    'Unable to save maintenance record.':
        'பராமரிப்பு பதிவை சேமிக்க முடியவில்லை.',
    'Maintenance updated successfully.':
        'பராமரிப்பு வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
    'Maintenance added successfully.':
        'பராமரிப்பு வெற்றிகரமாக சேர்க்கப்பட்டது.',
    'Unable to delete record.': 'பதிவை நீக்க முடியவில்லை.',
    'Maintenance record deleted.': 'பராமரிப்பு பதிவு நீக்கப்பட்டது.',
    'Service deleted successfully.': 'சேவை பதிவு வெற்றிகரமாக நீக்கப்பட்டது.',
    'Unable to delete service.': 'சேவை பதிவை நீக்க முடியவில்லை.',
    'No matching service records': 'பொருந்தும் சேவை பதிவுகள் எதுவும் இல்லை',
    'Try a different registration number or search term.':
        'வேறு பதிவு எண் அல்லது தேடல் சொல்லை முயற்சிக்கவும்.',
    'Vehicle deleted successfully': 'வாகனம் வெற்றிகரமாக நீக்கப்பட்டது',
    'Failed to delete vehicle': 'வாகனத்தை நீக்க முடியவில்லை',
    'Excavator deleted successfully': 'எக்ஸ்கவேட்டர் வெற்றிகரமாக நீக்கப்பட்டது',
    'Failed to delete excavator': 'எக்ஸ்கவேட்டரை நீக்க முடியவில்லை',
    'Something went wrong.': 'ஏதோ தவறு ஏற்பட்டது.',
    'Closing hour cannot be less than starting hour.':
        'முடிவு மணி, தொடக்க மணியை விட குறைவாக இருக்க முடியாது.',
    'Closing KM cannot be less than Starting KM.':
        'முடிவு கி.மீ., தொடக்க கி.மீ.யை விட குறைவாக இருக்க முடியாது.',
    'Enter a valid value': 'சரியான மதிப்பை உள்ளிடவும்',
    'File picker error: ': 'கோப்பு தேர்வு பிழை: ',
    'Failed to extract transport maintenance data: ':
        'போக்குவரத்து பராமரிப்பு தரவைப் பிரித்தெடுக்க முடியவில்லை: ',
    'Failed to extract transport service data: ':
        'போக்குவரத்து சேவை தரவைப் பிரித்தெடுக்க முடியவில்லை: ',
    'Enter quantity for at least one item.':
        'குறைந்தது ஒரு பொருளுக்காவது அளவை உள்ளிடவும்.',
    'Enter a valid unit price for every item with quantity.':
        'அளவு உள்ள ஒவ்வொரு பொருளுக்கும் சரியான அலகு விலையை உள்ளிடவும்.',
    'Purchase updated successfully.':
        'கொள்முதல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
    'Edit Blasting Material Purchase': 'பிளாஸ்டிங் பொருள் கொள்முதலை திருத்து',
    'New Blasting Material Purchase': 'புதிய பிளாஸ்டிங் பொருள் கொள்முதல்',
    'Loads: ': 'சுமைகள்: ',
    'Unknown error': 'தெரியாத பிழை',
    'Unknown': 'தெரியாதது',
    'Not Registered': 'பதிவு செய்யப்படவில்லை',
    'Manufacturer / Model': 'உற்பத்தியாளர் / மாடல்',
    'Normal': 'சாதாரணம்',
    'Last Service': 'கடைசி சேவை',
    'Current Meter': 'தற்போதைய மீட்டர்',
    'Next Service': 'அடுத்த சேவை',
    'Are you sure you want to delete the service record?':
        'இந்த சேவை பதிவை நீக்க விரும்புகிறீர்களா?',
    'Compliance report exported successfully.\n':
        'இணக்கப்பாட்டு அறிக்கை வெற்றிகரமாக ஏற்றுமதி செய்யப்பட்டது.\n',
    'Compliance report exported successfully.':
        'இணக்கப்பாட்டு அறிக்கை வெற்றிகரமாக ஏற்றுமதி செய்யப்பட்டது.',
    'Select': 'தேர்ந்தெடுக்கவும்',
    'Enter': 'உள்ளிடவும்',
    'KM': 'கி.மீ.',
    'Hrs': 'மணி',
    'Unknown Vehicle': 'தெரியாத வாகனம்',
    'Unknown Excavator': 'தெரியாத எக்ஸ்கவேட்டர்',
    'Transport maintenance updated successfully.':
        'போக்குவரத்து பராமரிப்பு வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
    'Transport maintenance added successfully.':
        'போக்குவரத்து பராமரிப்பு வெற்றிகரமாக சேர்க்கப்பட்டது.',
    'Edit Transport Vehicle': 'போக்குவரத்து வாகனத்தை திருத்து',
    'OPERATOR': 'ஆபரேட்டர்',
    'SHIFT': 'ஷிப்ட்',
    'HOURS': 'மணி நேரம்',
    'LOADS': 'சுமைகள்',
    'DIESEL': 'டீசல்',
    'EXPENSE': 'செலவு',
    'VEHICLE': 'வாகனம்',
    'DRIVER': 'ஓட்டுநர்',
    'ROUTE': 'வழித்தடம்',
  };
}
